version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-data:/prometheus
      - /etc/prometheus:/config
    command:
      - '--config.file=/config/prometheus.yaml'
    ports:
      - '9090:9090'
    networks:
      - network1
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - network1
    volumes:
      - grafana-data:/var/lib/grafana

  openam:
    image: openidentityplatform/openam:latest
    hostname: 192.168.29.67
    ports:
      - '8080:8080'
    networks:
      - network1
    volumes:
      - openam-data:/usr/openam/config

  registry:
    image: registry:2
    ports:
      - '5000:5000'
    networks:
      - network1
    
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - '8000:8080'
    networks:
      - network1
    volumes:
      - jenkins-data:/var/jenkins_home
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'
    networks:
      - network1

volumes:
  grafana-data:
  openam-data:
  jenkins-data:
  prometheus-data:
  
networks:
  network1:
